test_that("greater alternative", {
  demo_data <- rnorm(10, mean = 0, sd = 1)
  test_demo1 <- t.test(demo_data, alternative = "greater", mu = 0)
  # run the demo data with my function for one sided test
  test_demo <- my_t.test(demo_data, "greater", m = 0)
  exp_stat <- as.numeric(test_demo1$statistic)
  expect_equal(test_demo$test_stat, exp_stat)
  expect_equal(test_demo$df, 9)
  expect_equal(test_demo$alternative, "greater")
  expect_equal(test_demo$p_val, test_demo1$p.value)
})
test_that("two.sided alternative", {
  demo_data <- rnorm(10, mean = 0, sd = 1)
  test_demo <- my_t.test(demo_data, "two.sided", m = 0)
  test_demo1 <- t.test(demo_data, alternative = "two.sided", mu = 0)
  exp_stat <- as.numeric(test_demo1$statistic)
  expect_equal(test_demo$test_stat, exp_stat)
  expect_equal(test_demo$df, 9)
  expect_equal(test_demo$alternative, "two.sided")
  expect_equal(test_demo$p_val, test_demo1$p.value)
})
test_that("less alternative", {
  demo_data <- rnorm(10, mean = 0, sd = 1)
  test_demo <- my_t.test(demo_data, "less", m = 0)
  test_demo1 <- t.test(demo_data, alternative = "less", mu = 0)
  exp_stat <- as.numeric(test_demo1$statistic)
  expect_equal(test_demo$test_stat, exp_stat)
  expect_equal(test_demo$df, 9)
  expect_equal(test_demo$alternative, "less")
  expect_equal(test_demo$p_val, test_demo1$p.value)
})
test_that("alternative must be 'two.sided', 'less', or 'greater'", {
  demo_data <- rnorm(10, mean = 0, sd = 1)
  expect_error(my_t.test(demo_data, "grea", m = 0))
})
